# Generated by Django 3.2.16 on 2023-10-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_cycles_per_year', models.IntegerField(blank=True, null=True)),
                ('project_term', models.IntegerField(blank=True, null=True)),
                ('constant_throughput', models.BooleanField(blank=True, null=True)),
                ('project_ecap', models.IntegerField(blank=True, null=True)),
                ('project_min_e_capacity', models.IntegerField(blank=True, null=True)),
                ('project_e_losses', models.IntegerField(blank=True, null=True)),
                ('degradation_curve', models.JSONField(blank=True, default=dict, null=True)),
                ('incremental_tranche_dc_output', models.JSONField(blank=True, default=dict, null=True)),
                ('degradation_curve_tranche_gt_1', models.JSONField(blank=True, default=dict, null=True)),
                ('incremental_project_dc_output', models.JSONField(blank=True, default=dict, null=True)),
                ('degradation_with_pg_matrix', models.JSONField(blank=True, default=dict, null=True)),
                ('energy_capacity_before_losses', models.JSONField(blank=True, default=list, null=True)),
                ('tranche1_data', models.JSONField(blank=True, default=list, null=True)),
                ('tranche2_data', models.JSONField(blank=True, default=list, null=True)),
                ('result', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputDataTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_soh_delta', models.JSONField(blank=True, default=dict, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel.constantdata')),
            ],
        ),
    ]
