# Generated by Django 3.2.16 on 2023-10-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constantdata',
            old_name='project_cycles_per_year',
            new_name='annual_operating_cycles',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='degradation_curve',
            new_name='deterioration_curve_for_phase_greater_than1',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='project_e_losses',
            new_name='duration_of_project',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='project_ecap',
            new_name='electrical_capacity',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='energy_capacity_before_losses',
            new_name='initial_energy',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='project_min_e_capacity',
            new_name='minimum_capacity',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='degradation_curve_tranche_gt_1',
            new_name='performance_decay_with_performance_grid_matrix',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='degradation_with_pg_matrix',
            new_name='performance_deterioration_profile',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='tranche1_data',
            new_name='phase1_data',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='tranche2_data',
            new_name='phase2_data',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='incremental_project_dc_output',
            new_name='progressive_project_direct_current_generation',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='constant_throughput',
            new_name='steady_output',
        ),
        migrations.RenameField(
            model_name='constantdata',
            old_name='incremental_tranche_dc_output',
            new_name='stepwise_direct_current_generation_increase',
        ),
        migrations.RemoveField(
            model_name='constantdata',
            name='project_term',
        ),
        migrations.AddField(
            model_name='constantdata',
            name='losses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
